version: '3'
services:
  auth:
    build: ./Auth
    tty: true # /bin/bashを実行しているので、ttyを割り当てないと継続して実行できない
    volumes:
      - ./Auth:/App
    ports:
      - "5000:5000"
  api:
    build: ./Api
    tty: true
    volumes:
      - ./Api:/App
    ports:
      - "5001:5001"